<!DOCTYPE html>
<html lang='en'>

  <head>
    <?php include 'layout/header.phtml' ?>
  </head>

  <body>

    <header>
      <?php include 'layout/navigation.phtml' ?>
    </header>


    <main>
      <img src="img/site/quickstart.png" alt="quickstart banner">
      <h1>This Is the home page</h1>
      <?= DB_TYPE ?>
      <br>
      <button id="btn">CLICK ME</button>
      <p id="demo"></p>
    </main>


    <footer>
      <?php include 'layout/footer.phtml' ?>
    </footer>

    <script src="/js/site/home.js"></script>
  </body>

</html>
